In [1]:
import climasus as cs

# Equivalente ao pipeline R em uma chamada
rel = cs.sus_pipeline(
    system="SIM-DO",
    uf="AC",
    year=2023,
    lang="pt",
    groups="respiratory",   # filtra grupo de doenças "respiratory"
    age_group=True,         # cria faixas etárias (equiv. create_age_groups = TRUE)
)

# Materializar como DataFrame pandas
df_analise = rel.df()  # ou .to_df() se preferir; .df() funciona com a API do projeto

In [2]:
rel = cs.sus_import(system="SIM-DO", uf="AC", year=2023, cache_dir="dados/cache", verbose=True)

In [3]:
rel.df()

,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,...,FONTES,TPRESGINFO,TPNIVELINV,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA,CONTADOR
0,1,2,01012023,0610,812,120070,26011941,481,1,4,...,,,,,,,,,,2067
1,1,2,01012023,1305,813,130180,20081966,456,2,4,...,,,,,,,,,,2146
2,1,2,01012023,0020,812,120030,15061968,454,2,1,...,,,,,,,,,,2196
3,1,2,01012023,1430,812,120045,14111965,457,1,4,...,,,,,,,,,,2839
4,1,2,01012023,1040,812,120035,12021958,464,2,4,...,,,,,,,,,,3066
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4184,1,2,31122023,0344,812,120020,09032023,309,2,5,...,SXXSXX,,,,29042024,3,28042024,,2,1462948
4185,1,2,31122023,0900,812,120043,29082023,304,1,5,...,SXXSXX,,,,14062024,3,12062024,,1,1464431
4186,1,2,31122023,1252,815,150650,12111929,494,2,1,...,,,,,,,,,,1465333
4187,1,2,14062023,0600,812,120034,03111930,492,2,5,...,,,,,,,,,,1465563
4188,1,2,08102023,,812,120034,16062023,303,1,5,...,SXXSXX,,,,16022024,3,15022024,,1,1465593

In [4]:
rel = cs.sus_clean(rel, fix_enc=True, dedup=True)
rel.df()

,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,...,FONTES,TPRESGINFO,TPNIVELINV,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA,CONTADOR
0,1,2,27122023,1100,812,120020,27122023,001,1,4,...,,,,,,,,,,1447749
1,1,2,06042023,0430,812,120010,06042023,101,2,4,...,,,,,,,,,,363984
2,1,2,24072023,1124,812,120050,24072023,011,2,4,...,SXSSXX,,,,14122023,3,14122023,,1,822603
3,1,2,31012023,1930,812,120030,31012023,107,1,5,...,SXSSXX,,,,01092023,3,16082023,,2,115029
4,1,2,26102023,1930,812,120020,26102023,036,1,4,...,,,,,,,,,,1200140
5,1,2,06012023,1020,812,120010,06012023,109,2,4,...,SSXSXX,,,,19092024,3,09072024,,1,21108
6,1,2,15072023,1921,812,120040,15072023,102,2,4,...,SXSSXX,,,,26102023,3,31082023,,2,785910
7,1,2,25062023,1600,812,120040,25062023,102,2,1,...,SXSSXX,,,,15082023,3,03082023,,2,701654
8,1,2,16092023,2000,812,120040,16092023,104,2,1,...,SXSSXX,,,,11122023,3,08122023,,1,1040731
9,1,2,02022023,2250,812,120020,02022023,045,1,4,...,SXSSXX,,,,26062023,3,13032023,,2,122556
10,1,2,11042023,1335,812,120043,11042023,120,1,4,...,SXSSXX,,,,17102023,3,06092023,,1,384521
11,1,2,10112023,1535,812,120040,10112023,104,1,,...,SXSSXX,,,,18122023,3,13122023,,1,1257010
12,1,2,03042023,0913,812,120050,03042023,020,1,4,...,SXSXXX,,,,13122023,3,13122023,,1,353722
13,1,2,07072023,2131,812,120040,07072023,104,1,4,...,SXSXXX,,,,08082023,3,27072023,,2,751913
14,1,2,08032023,0725,812,120020,08032023,045,2,4,...,XXSXXX,,,,11052023,3,30062023,,1,253372
15,1,2,25062023,1945,812,120040,25062023,105,1,1,...,SXSSXX,,,,26102023,3,08082023,,2,701314
16,1,2,19052023,1040,812,120050,19052023,103,1,4,...,XXSSXX,,,,24112023,3,31102023,,1,540179
17,1,2,11072023,1600,812,120020,11072023,101,1,4,...,SXSSXX,,,,11082023,3,17072023,,2,768844
18,1,2,29082023,1502,812,120040,29082023,101,1,,...,SXSSXX,,,,12122023,3,29112023,,1,968874
19,1,2,23042023,2025,812,120060,23042023,102,1,5,...,SXXSXX,,,,20022024,3,19022024,,2,432800
20,1,2,24042023,2059,812,120030,24042023,105,2,5,...,SSSSXX,,,,13062023,2,12062023,,2,435672
21,1,2,16072023,2055,812,120043,16072023,108,2,5,...,SXSSXX,,,,14052024,3,25042024,,1,790397
22,1,2,31072023,0326,812,120050,30072023,114,2,4,...,SXSSXX,,,,12122023,3,12122023,,1,851705
23,1,2,23082023,2145,812,120040,23082023,107,1,4,...,SXSSXX,,,,22112023,3,22112023,,1,945394
24,1,2,23082023,1723,812,120050,23082023,102,2,1,...,SXSSXX,,,,14122023,3,14122023,,1,946222
25,1,2,18112023,1613,812,120040,18112023,101,1,4,...,SXSSXX,,,,02052024,3,04042024,,1,1291872
26,1,2,13092023,1305,812,120020,13092023,101,2,1,...,,,,,,,,,,1026962
27,1,2,19092023,1710,812,120020,19092023,101,2,4,...,SXSSXX,,,,18012024,3,06102023,,1,1054242
28,1,2,15032023,1630,812,120040,15032023,055,1,4,...,,,,,,,,,,278707
29,1,2,28072023,0449,812,120040,28072023,045,1,4,...,XXSSXX,,,,20092023,3,,,2,840345
30,1,2,13092023,1920,812,120050,13092023,005,1,4,...,SXSSXX,,,,19032024,3,14032024,,1,1027098
31,1,2,08082023,1110,812,120040,08082023,109,2,4,...,SXSSXX,,,,22112023,3,20112023,,1,886181
32,1,2,09102023,2322,812,120060,09102023,101,1,4,...,,,,,,,,,,1130910
33,1,2,14052023,1930,812,120040,14052023,120,2,4,...,SXSXXX,,,,15082023,3,,,2,518521
34,1,2,27022023,0030,812,120020,27022023,015,2,4,...,,,,,,,,,,218779
35,1,2,03082023,1913,812,120040,03082023,001,2,4,...,SSSSXX,,,,27102023,3,27102023,,2,864594

In [5]:
rel = cs.sus_standardize(rel, lang="pt", system="SIM-DO")
rel.df()

,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,...,FONTES,TPRESGINFO,TPNIVELINV,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA,CONTADOR
0,1,2,NaT,1305,812,120020,NaT,101,2,1,...,,,,,,,,,,1026962
1,1,2,NaT,1710,812,120020,NaT,101,2,4,...,SXSSXX,,,,18012024,3,06102023,,1,1054242
2,1,2,NaT,1630,812,120040,NaT,055,1,4,...,,,,,,,,,,278707
3,1,2,NaT,0449,812,120040,NaT,045,1,4,...,XXSSXX,,,,20092023,3,,,2,840345
4,1,2,NaT,1502,812,120040,NaT,101,1,,...,SXSSXX,,,,12122023,3,29112023,,1,968874
5,1,2,NaT,1920,812,120050,NaT,005,1,4,...,SXSSXX,,,,19032024,3,14032024,,1,1027098
6,1,2,NaT,1110,812,120040,NaT,109,2,4,...,SXSSXX,,,,22112023,3,20112023,,1,886181
7,1,2,NaT,1100,812,120020,NaT,001,1,4,...,,,,,,,,,,1447749
8,1,2,NaT,0430,812,120010,NaT,101,2,4,...,,,,,,,,,,363984
9,1,2,NaT,1124,812,120050,NaT,011,2,4,...,SXSSXX,,,,14122023,3,14122023,,1,822603
10,1,2,NaT,1040,812,120050,NaT,103,1,4,...,XXSSXX,,,,24112023,3,31102023,,1,540179
11,1,2,NaT,1600,812,120020,NaT,101,1,4,...,SXSSXX,,,,11082023,3,17072023,,2,768844
12,1,2,NaT,1930,812,120020,NaT,036,1,4,...,,,,,,,,,,1200140
13,1,2,NaT,1020,812,120010,NaT,109,2,4,...,SSXSXX,,,,19092024,3,09072024,,1,21108
14,1,2,NaT,1921,812,120040,NaT,102,2,4,...,SXSSXX,,,,26102023,3,31082023,,2,785910
15,1,2,NaT,0030,812,120020,NaT,015,2,4,...,,,,,,,,,,218779
16,1,2,NaT,1913,812,120040,NaT,001,2,4,...,SSSSXX,,,,27102023,3,27102023,,2,864594
17,1,2,NaT,2131,812,120040,NaT,104,1,4,...,SXSXXX,,,,08082023,3,27072023,,2,751913
18,1,2,NaT,2025,812,120060,NaT,102,1,5,...,SXXSXX,,,,20022024,3,19022024,,2,432800
19,1,2,NaT,2059,812,120030,NaT,105,2,5,...,SSSSXX,,,,13062023,2,12062023,,2,435672
20,1,2,NaT,2055,812,120043,NaT,108,2,5,...,SXSSXX,,,,14052024,3,25042024,,1,790397
21,1,2,NaT,0326,812,120050,NaT,114,2,4,...,SXSSXX,,,,12122023,3,12122023,,1,851705
22,1,2,NaT,2145,812,120040,NaT,107,1,4,...,SXSSXX,,,,22112023,3,22112023,,1,945394
23,1,2,NaT,1723,812,120050,NaT,102,2,1,...,SXSSXX,,,,14122023,3,14122023,,1,946222
24,1,2,NaT,1535,812,120040,NaT,104,1,,...,SXSSXX,,,,18122023,3,13122023,,1,1257010
25,1,2,NaT,0913,812,120050,NaT,020,1,4,...,SXSXXX,,,,13122023,3,13122023,,1,353722
26,1,2,NaT,0725,812,120020,NaT,045,2,4,...,XXSXXX,,,,11052023,3,30062023,,1,253372
27,1,2,NaT,1945,812,120040,NaT,105,1,1,...,SXSSXX,,,,26102023,3,08082023,,2,701314
28,1,2,NaT,1600,812,120040,NaT,102,2,1,...,SXSSXX,,,,15082023,3,03082023,,2,701654
29,1,2,NaT,2322,812,120060,NaT,101,1,4,...,,,,,,,,,,1130910
30,1,2,NaT,1930,812,120040,NaT,120,2,4,...,SXSXXX,,,,15082023,3,,,2,518521
31,1,2,NaT,1613,812,120040,NaT,101,1,4,...,SXSSXX,,,,02052024,3,04042024,,1,1291872
32,1,2,NaT,1930,812,120030,NaT,107,1,5,...,SXSSXX,,,,01092023,3,16082023,,2,115029
33,1,2,NaT,2000,812,120040,NaT,104,2,1,...,SXSSXX,,,,11122023,3,08122023,,1,1040731
34,1,2,NaT,2250,812,120020,NaT,045,1,4,...,SXSSXX,,,,26062023,3,13032023,,2,122556
35,1,2,NaT,1335,812,120043,NaT,120,1,4,...,SXSSXX,,,,17102023,3,06092023,,1,384521

In [6]:
rel = cs.sus_variables(rel, age_group=True)
rel.df()

,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,...,TPRESGINFO,TPNIVELINV,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA,CONTADOR,age_group
0,1,2,NaT,2025,812,120060,NaT,102,1,5,...,,,,20022024,3,19022024,,2,432800,65-998
1,1,2,NaT,2059,812,120030,NaT,105,2,5,...,,,,13062023,2,12062023,,2,435672,65-998
2,1,2,NaT,2055,812,120043,NaT,108,2,5,...,,,,14052024,3,25042024,,1,790397,65-998
3,1,2,NaT,0326,812,120050,NaT,114,2,4,...,,,,12122023,3,12122023,,1,851705,65-998
4,1,2,NaT,2145,812,120040,NaT,107,1,4,...,,,,22112023,3,22112023,,1,945394,65-998
5,1,2,NaT,1723,812,120050,NaT,102,2,1,...,,,,14122023,3,14122023,,1,946222,65-998
6,1,2,NaT,2322,812,120060,NaT,101,1,4,...,,,,,,,,,1130910,65-998
7,1,2,NaT,1930,812,120040,NaT,120,2,4,...,,,,15082023,3,,,2,518521,65-998
8,1,2,NaT,1930,812,120030,NaT,107,1,5,...,,,,01092023,3,16082023,,2,115029,65-998
9,1,2,NaT,1305,812,120020,NaT,101,2,1,...,,,,,,,,,1026962,65-998
10,1,2,NaT,1710,812,120020,NaT,101,2,4,...,,,,18012024,3,06102023,,1,1054242,65-998
11,1,2,NaT,1630,812,120040,NaT,055,1,4,...,,,,,,,,,278707,18-64
12,1,2,NaT,0449,812,120040,NaT,045,1,4,...,,,,20092023,3,,,2,840345,18-64
13,1,2,NaT,1100,812,120020,NaT,001,1,4,...,,,,,,,,,1447749,0-17
14,1,2,NaT,0430,812,120010,NaT,101,2,4,...,,,,,,,,,363984,65-998
15,1,2,NaT,1124,812,120050,NaT,011,2,4,...,,,,14122023,3,14122023,,1,822603,0-17
16,1,2,NaT,1930,812,120020,NaT,036,1,4,...,,,,,,,,,1200140,18-64
17,1,2,NaT,1020,812,120010,NaT,109,2,4,...,,,,19092024,3,09072024,,1,21108,65-998
18,1,2,NaT,1921,812,120040,NaT,102,2,4,...,,,,26102023,3,31082023,,2,785910,65-998
19,1,2,NaT,1040,812,120050,NaT,103,1,4,...,,,,24112023,3,31102023,,1,540179,65-998
20,1,2,NaT,1600,812,120020,NaT,101,1,4,...,,,,11082023,3,17072023,,2,768844,65-998
21,1,2,NaT,1920,812,120050,NaT,005,1,4,...,,,,19032024,3,14032024,,1,1027098,0-17
22,1,2,NaT,1110,812,120040,NaT,109,2,4,...,,,,22112023,3,20112023,,1,886181,65-998
23,1,2,NaT,0030,812,120020,NaT,015,2,4,...,,,,,,,,,218779,0-17
24,1,2,NaT,1913,812,120040,NaT,001,2,4,...,,,,27102023,3,27102023,,2,864594,0-17
25,1,2,NaT,1502,812,120040,NaT,101,1,,...,,,,12122023,3,29112023,,1,968874,65-998
26,1,2,NaT,2000,812,120040,NaT,104,2,1,...,,,,11122023,3,08122023,,1,1040731,65-998
27,1,2,NaT,2250,812,120020,NaT,045,1,4,...,,,,26062023,3,13032023,,2,122556,18-64
28,1,2,NaT,1335,812,120043,NaT,120,1,4,...,,,,17102023,3,06092023,,1,384521,65-998
29,1,2,NaT,2131,812,120040,NaT,104,1,4,...,,,,08082023,3,27072023,,2,751913,65-998
30,1,2,NaT,0725,812,120020,NaT,045,2,4,...,,,,11052023,3,30062023,,1,253372,18-64
31,1,2,NaT,1945,812,120040,NaT,105,1,1,...,,,,26102023,3,08082023,,2,701314,65-998
32,1,2,NaT,1613,812,120040,NaT,101,1,4,...,,,,02052024,3,04042024,,1,1291872,65-998
33,1,2,NaT,1535,812,120040,NaT,104,1,,...,,,,18122023,3,13122023,,1,1257010,65-998
34,1,2,NaT,0913,812,120050,NaT,020,1,4,...,,,,13122023,3,13122023,,1,353722,18-64
35,1,2,NaT,1600,812,120040,NaT,102,2,1,...,,,,15082023,3,03082023,,2,701654,65-998

In [ ]:
rel = cs.sus_variables(rel, age_group=True)
rel.df()

,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,...,TPNIVELINV,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA,CONTADOR,age_group,age_group_1
0,1,2,NaT,1305,812,120020,NaT,101,2,1,...,,,,,,,,1026962,65-998,65-998
1,1,2,NaT,1710,812,120020,NaT,101,2,4,...,,,18012024,3,06102023,,1,1054242,65-998,65-998
2,1,2,NaT,1630,812,120040,NaT,055,1,4,...,,,,,,,,278707,18-64,18-64
3,1,2,NaT,0449,812,120040,NaT,045,1,4,...,,,20092023,3,,,2,840345,18-64,18-64
4,1,2,NaT,1920,812,120050,NaT,005,1,4,...,,,19032024,3,14032024,,1,1027098,0-17,0-17
5,1,2,NaT,1110,812,120040,NaT,109,2,4,...,,,22112023,3,20112023,,1,886181,65-998,65-998
6,1,2,NaT,1930,812,120020,NaT,036,1,4,...,,,,,,,,1200140,18-64,18-64
7,1,2,NaT,1020,812,120010,NaT,109,2,4,...,,,19092024,3,09072024,,1,21108,65-998,65-998
8,1,2,NaT,1921,812,120040,NaT,102,2,4,...,,,26102023,3,31082023,,2,785910,65-998,65-998
9,1,2,NaT,2000,812,120040,NaT,104,2,1,...,,,11122023,3,08122023,,1,1040731,65-998,65-998
10,1,2,NaT,2250,812,120020,NaT,045,1,4,...,,,26062023,3,13032023,,2,122556,18-64,18-64
11,1,2,NaT,1335,812,120043,NaT,120,1,4,...,,,17102023,3,06092023,,1,384521,65-998,65-998
12,1,2,NaT,1600,812,120040,NaT,102,2,1,...,,,15082023,3,03082023,,2,701654,65-998,65-998
13,1,2,NaT,1613,812,120040,NaT,101,1,4,...,,,02052024,3,04042024,,1,1291872,65-998,65-998
14,1,2,NaT,1100,812,120020,NaT,001,1,4,...,,,,,,,,1447749,0-17,0-17
15,1,2,NaT,0430,812,120010,NaT,101,2,4,...,,,,,,,,363984,65-998,65-998
16,1,2,NaT,1124,812,120050,NaT,011,2,4,...,,,14122023,3,14122023,,1,822603,0-17,0-17
17,1,2,NaT,2025,812,120060,NaT,102,1,5,...,,,20022024,3,19022024,,2,432800,65-998,65-998
18,1,2,NaT,2059,812,120030,NaT,105,2,5,...,,,13062023,2,12062023,,2,435672,65-998,65-998
19,1,2,NaT,2055,812,120043,NaT,108,2,5,...,,,14052024,3,25042024,,1,790397,65-998,65-998
20,1,2,NaT,0326,812,120050,NaT,114,2,4,...,,,12122023,3,12122023,,1,851705,65-998,65-998
21,1,2,NaT,2145,812,120040,NaT,107,1,4,...,,,22112023,3,22112023,,1,945394,65-998,65-998
22,1,2,NaT,1723,812,120050,NaT,102,2,1,...,,,14122023,3,14122023,,1,946222,65-998,65-998
23,1,2,NaT,2322,812,120060,NaT,101,1,4,...,,,,,,,,1130910,65-998,65-998
24,1,2,NaT,1930,812,120040,NaT,120,2,4,...,,,15082023,3,,,2,518521,65-998,65-998
25,1,2,NaT,1040,812,120050,NaT,103,1,4,...,,,24112023,3,31102023,,1,540179,65-998,65-998
26,1,2,NaT,1600,812,120020,NaT,101,1,4,...,,,11082023,3,17072023,,2,768844,65-998,65-998
27,1,2,NaT,1930,812,120030,NaT,107,1,5,...,,,01092023,3,16082023,,2,115029,65-998,65-998
28,1,2,NaT,1502,812,120040,NaT,101,1,,...,,,12122023,3,29112023,,1,968874,65-998,65-998
29,1,2,NaT,0725,812,120020,NaT,045,2,4,...,,,11052023,3,30062023,,1,253372,18-64,18-64
30,1,2,NaT,1945,812,120040,NaT,105,1,1,...,,,26102023,3,08082023,,2,701314,65-998,65-998
31,1,2,NaT,2131,812,120040,NaT,104,1,4,...,,,08082023,3,27072023,,2,751913,65-998,65-998
32,1,2,NaT,1535,812,120040,NaT,104,1,,...,,,18122023,3,13122023,,1,1257010,65-998,65-998
33,1,2,NaT,0913,812,120050,NaT,020,1,4,...,,,13122023,3,13122023,,1,353722,18-64,18-64
34,1,2,NaT,0030,812,120020,NaT,015,2,4,...,,,,,,,,218779,0-17,0-17
35,1,2,NaT,1913,812,120040,NaT,001,2,4,...,,,27102023,3,27102023,,2,864594,0-17,0-17

: